name: mlflow-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow>=2.9.0
      - scikit-learn==1.3.2
      - pandas
      - numpy
      - matplotlib
      - seaborn